# Generated by Django 4.2 on 2023-05-03 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_student_admin_alter_student_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='app.courses'),
        ),
    ]
