# Generated by Django 4.2 on 2023-05-20 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_staff_notification_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_notification',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff'),
        ),
    ]
